name: Fix Backend Code Style

on:
  push:
    paths:
      - 'backend/**'
    branches: ["master", "develop"]
  pull_request:
    branches: ["master", "develop"]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: [8.2]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: json, dom, curl, libxml, mbstring
          coverage: none

      - name: Install Pint
        run: composer global require laravel/pint

      - name: Run Pint
        working-directory: backend
        run: pint

      - name: Commit linted files
        uses: stefanzweifel/git-auto-commit-action@v5
